import Navigation from "./components/Navigation";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja">
      <body>
        <div className="flex flex-col min-h-screen">
          <Navigation />

          <main className="flex-1 container max-w-screen-xl mx-auto px-5 py-5">
            {children}
          </main>

          <footer className="border-t py-5">
            <div className="text-center text-sm">KagariChannel</div>
          </footer>
        </div>
      </body>
    </html>
  );
}
